#!/bin/sh

#https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa

echo "Server script started"

cd $HOME/eosio-react-app

echo "ls -la"
ls -la

echo "git remote -v"
git remote -v

echo "git pull origin"
#git pull origin
git pull $HOME/project.git devops

git --work-tree=$HOME/working-tree-project.git checkout -f devops

echo "Server script competed"