#!/bin/sh

echo "Server script started"

cd $HOME/eosio-react-app

echo "ls -la"
ls -la

echo "git remote -v"
git remote -v

echo "git pull origin"
#git pull origin
git pull $HOME/project.git devops

echo "Server script competed"