#!/bin/sh

#https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa

echo "Server script started"

#echo "git stash"
#git --work-tree=$HOME/working-tree-project.git stash
#git --work-tree=$HOME/working-tree-project.git status

echo "git checkout -f devops"
git --work-tree=$HOME/working-tree-project.git --git-dir=$HOME/project.git checkout -f devops
# git --work-tree=$HOME/working-tree-project.git status

echo "git reset devops"
git --work-tree=$HOME/working-tree-project.git reset devops
# git --work-tree=$HOME/working-tree-project.git status

echo "git checkout -f devops"
git --work-tree=$HOME/working-tree-project.git checkout -f devops
# git --work-tree=$HOME/working-tree-project.git status

echo "Server script competed"