FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y --no-install-recommends wget ca-certificates software-properties-common
RUN wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.7.0/eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb \
    && apt install -y ./eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb \
    && rm eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb
RUN wget https://github.com/dfuse-io/eos/releases/download/v2.0.3-dm/eosio_2.0.3-dm_ubuntu-18.04_amd64.deb \
    && apt install -y ./eosio_2.0.3-dm_ubuntu-18.04_amd64.deb \
    && rm eosio_2.0.3-dm_ubuntu-18.04_amd64.deb
RUN wget https://github.com/dfuse-io/dfuse-eosio/releases/download/v0.1.0-beta2/dfuse-eosio_0.1.0-beta2_linux_x86_64.tar.gz \
    && tar -xzvf dfuse-eosio_0.1.0-beta2_linux_x86_64.tar.gz \
    && rm dfuse-eosio_0.1.0-beta2_linux_x86_64.tar.gz
RUN mv dfuseeos /usr/local/bin/dfuseeos
RUN mkdir ./dfuse-init && cd dfuse-init
RUN (echo "y" && cat) | dfuseeos init # "y" will initialize to run a producing node, "n" will connect to existing node
RUN apt-get remove -y wget ca-certificates
RUN apt-get autoremove -y

# docker run -p 13013:13013 -p 8888:8888 -p 8081:8081 -p 8080:8080 -it {{image_name}} dfuseeos start