 
FROM ubuntu:18.04
RUN apt-get update \
    && apt-get install -y --no-install-recommends wget ca-certificates software-properties-common \
    && wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.7.0/eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb \
    && apt install -y ./eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb \
    && rm eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb \
    && wget https://github.com/dfuse-io/eos/releases/download/v2.0.3-dm/eosio_2.0.3-dm_ubuntu-18.04_amd64.deb \
    && apt install -y ./eosio_2.0.3-dm_ubuntu-18.04_amd64.deb \
    && rm eosio_2.0.3-dm_ubuntu-18.04_amd64.deb \
    && wget https://github.com/dfuse-io/dfuse-eosio/releases/download/v0.1.0-beta2/dfuse-eosio_0.1.0-beta2_linux_x86_64.tar.gz \
    && tar -xzvf dfuse-eosio_0.1.0-beta2_linux_x86_64.tar.gz \
    && rm dfuse-eosio_0.1.0-beta2_linux_x86_64.tar.gz
RUN mv dfuseeos /usr/local/bin/dfuseeos \
    && apt-get remove -y wget ca-certificates \
    && apt-get autoremove -y \
#    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && cd /usr/opt/eosio.cdt/1.7.0/bin \
    # Hack to fix multithreading issue in eosio.cdt 1.7.0
    && mv wasm-ld wasm-ld.real \
    && echo '#!/bin/bash' > wasm-ld \
    && echo '`dirname $0`/wasm-ld.real --no-threads "$@"' >> wasm-ld \
    && chmod +x /usr/opt/eosio.cdt/1.7.0/bin/wasm-ld
RUN cd / \
    # "y" will initialize to run a producing node, "n" will connect to existing node
    && (echo "y" && cat) | dfuseeos init
RUN cat producer/config.ini
RUN sed -i 's/127.0.0.1:8888/0.0.0.0:8888/g' producer/config.ini
RUN cat producer/config.ini

CMD dfuseeos start --data-dir /data  >> /data/dfuse.log 2>&1
# docker run -p 8888:8888 -p 8081:8081 -p 8080:8080 -it 719b3cb3da24 dfuseeos start